name: pos_tpt_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  _fe_analyzer_shared: ^55.0.0
  android_path_provider: ^0.3.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  flutter_localization: ^0.1.12
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^8.0.0
  form_builder_validators: ^9.0.0
  freezed: ^2.3.2
  get: ^4.6.5
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  logger: ^1.2.2
  modal_bottom_sheet: ^3.0.0-pre
  permission_handler: ^10.2.0
  pull_to_refresh: ^2.0.0
  qr_code_scanner: ^1.0.1
  retrofit: any
  retrofit_generator: any
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  sizer: ^2.0.15

dev_dependencies:
  build_runner: any
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/resources/

flutter:
  uses-material-design: true
  assets:
    - lib/resources/images/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Light.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-SemiBold.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
