// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkC0v1yi16FCSbSqIgQPB3lO5ViLJwomM',
    appId: '1:57783405919:web:09643088106f4bb90dfaea',
    messagingSenderId: '57783405919',
    projectId: 'toko-perlengkapan-ternak',
    authDomain: 'toko-perlengkapan-ternak.firebaseapp.com',
    storageBucket: 'toko-perlengkapan-ternak.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpToyl2vIwAw2YDQOvjALim4FAqw7evYU',
    appId: '1:57783405919:android:ce2c56fbcc0d88540dfaea',
    messagingSenderId: '57783405919',
    projectId: 'toko-perlengkapan-ternak',
    storageBucket: 'toko-perlengkapan-ternak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2c926nVFvbWr2P2Zn3aEEfP3s9Nj2njQ',
    appId: '1:57783405919:ios:19ac0a0d4f865bbf0dfaea',
    messagingSenderId: '57783405919',
    projectId: 'toko-perlengkapan-ternak',
    storageBucket: 'toko-perlengkapan-ternak.appspot.com',
    iosBundleId: 'com.rahdeva.posTptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2c926nVFvbWr2P2Zn3aEEfP3s9Nj2njQ',
    appId: '1:57783405919:ios:08e15006aeefff050dfaea',
    messagingSenderId: '57783405919',
    projectId: 'toko-perlengkapan-ternak',
    storageBucket: 'toko-perlengkapan-ternak.appspot.com',
    iosBundleId: 'com.rahdeva.posTptApp.RunnerTests',
  );
}
